1. Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır. 

In [12]:
import numpy as np

array = np.array([10, 20, 30, 40, 50], dtype=np.int32)

boyut = array.ndim 
eleman_sayisi = array.size 

print(f"Array: {array}")
print(f"Arrayin boyutu: {boyut}")
print(f"Arrayin eleman sayısı: {eleman_sayisi}")

Array: [10 20 30 40 50]
Arrayin boyutu: 1
Arrayin eleman sayısı: 5


2. İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır. 

In [13]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                     [[10, 11, 12], [13, 14, 15], [16, 17, 18]]], dtype=np.int32)

boyut_3d = array_3d.ndim  
eleman_sayisi_3d = array_3d.size  
katman_sayisi_3d, satir_sayisi_3d, sutun_sayisi_3d = array_3d.shape  

print(f"3D Array: {array_3d}")
print(f"3D Arrayin boyutu: {boyut_3d}")
print(f"3D Arrayin eleman sayısı: {eleman_sayisi_3d}")
print(f"3D Arrayin katman sayısı: {katman_sayisi_3d}")
print(f"3D Arrayin satır sayısı: {satir_sayisi_3d}")
print(f"3D Arrayin sütun sayısı: {sutun_sayisi_3d}")


print("Indexleme:")
print(f"İlk katman, ilk satır, ilk sütun: {array_3d[0, 0, 0]}")  
print(f"İkinci katman, ikinci satır, ikinci sütun: {array_3d[1, 1, 1]}")  

print("Dilimleme (Slicing):")
print("İlk katman: ", array_3d[0])  
print("İkinci katmanın ilk iki satırı: ", array_3d[1, :2])  


3D Array: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3D Arrayin boyutu: 3
3D Arrayin eleman sayısı: 18
3D Arrayin katman sayısı: 2
3D Arrayin satır sayısı: 3
3D Arrayin sütun sayısı: 3
Indexleme:
İlk katman, ilk satır, ilk sütun: 1
İkinci katman, ikinci satır, ikinci sütun: 14
Dilimleme (Slicing):
İlk katman:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
İkinci katmanın ilk iki satırı:  [[10 11 12]
 [13 14 15]]


3. Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır 

In [14]:
array_1d = np.array([10, 20, 30, 40, 50])

print(f"1D Array: {array_1d}")
print(f"İlk eleman: {array_1d[0]}") 
print(f"Son eleman: {array_1d[-1]}") 


print(f"İlk üç eleman: {array_1d[:3]}") 
print(f"Son iki eleman: {array_1d[-2:]}") 
print(f"Ortadaki elemanlar: {array_1d[1:4]}") 

1D Array: [10 20 30 40 50]
İlk eleman: 10
Son eleman: 50
İlk üç eleman: [10 20 30]
Son iki eleman: [40 50]
Ortadaki elemanlar: [20 30 40]


In [15]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])


print(f"2D Array: {array_2d}")
print(f"İlk satır, ikinci sütun: {array_2d[0, 1]}") 
print(f"İkinci satır, üçüncü sütun: {array_2d[1, 2]}") 

print("Dilimleme (Slicing):")
print(f"İlk satır: {array_2d[0, :]}")  
print(f"İkinci satır: {array_2d[1, :]}") 
print(f"İlk iki sütun: {array_2d[:, :2]}")  

2D Array: [[1 2 3]
 [4 5 6]]
İlk satır, ikinci sütun: 2
İkinci satır, üçüncü sütun: 6
Dilimleme (Slicing):
İlk satır: [1 2 3]
İkinci satır: [4 5 6]
İlk iki sütun: [[1 2]
 [4 5]]


In [8]:
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


print(f"3D Array: {array_3d}")
print(f"İlk katman, ilk satır, ikinci sütun: {array_3d[0, 0, 1]}") 
print(f"İkinci katman, ikinci satır, üçüncü sütun: {array_3d[1, 1, 2]}") 

print("Dilimleme (Slicing):")
print(f"İlk katman: {array_3d[0, :, :]}")
print(f"İkinci katmanın ilk satırı: {array_3d[1, 0, :]}")
print(f"Tüm katmanların ilk iki sütunu: {array_3d[:, :, :2]}") 

3D Array: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
İlk katman, ilk satır, ikinci sütun: 2
İkinci katman, ikinci satır, üçüncü sütun: 12
Dilimleme (Slicing):
İlk katman: [[1 2 3]
 [4 5 6]]
İkinci katmanın ilk satırı: [7 8 9]
Tüm katmanların ilk iki sütunu: [[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


Açıklama: 
1. Bir boyutlu array (1D): np.array([10, 20, 30, 40, 50]) kullanarak bir boyutlu array oluşturduk ve üzerinde indeksleme ve dilimleme yaptık.
2. İki boyutlu array (2D): np.array([[1, 2, 3], [4, 5, 6]]) ile iki boyutlu bir array oluşturduk. Satır ve sütun bilgilerine göre hem indexleme hem de dilimleme işlemleri yaptık.
3. Üç boyutlu array (3D): np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) ile üç boyutlu bir array oluşturduk. Üç boyutlu bir dizide, katman, satır ve sütun indekslerine göre dilimleme ve indexleme işlemlerini gerçekleştirdik.


-
-
-
-
-
-
-

4. Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir. 

In [16]:
zeros_array = np.zeros((2, 3), dtype=np.int32)
print("Sıfırlardan oluşan array:")
print(zeros_array)

ones_array = np.ones((2, 3), dtype=np.int32)
print("Birlerden oluşan array:")
print(ones_array)

combined_rows = np.vstack((zeros_array, ones_array))
print("Satır bazında birleştirilmiş array (dikey):")
print(combined_rows)

combined_columns = np.hstack((zeros_array, ones_array))
print("Sütun bazında birleştirilmiş array (yatay):")
print(combined_columns)


Sıfırlardan oluşan array:
[[0 0 0]
 [0 0 0]]
Birlerden oluşan array:
[[1 1 1]
 [1 1 1]]
Satır bazında birleştirilmiş array (dikey):
[[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]
Sütun bazında birleştirilmiş array (yatay):
[[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
